name: Set up Linux environment
description: Set up everything needed to build and release things on Linux
inputs:
  aws-access-key-id:
    required: true
    description: The aws-access-key-id used to authenticate with AWS
  aws-secret-access-key:
    required: true
    description: The aws-secret-access-key used to authenticate with AWS
  cloudflare-email:
    required: true
    description: The email used to authenticate with Cloudflare
  cloudflare-token:
    required: true
    description: The token used to authenticate with Cloudflare
runs:
  using: composite
  steps:
    - name: Configure git
      run: |
        git config --global user.name "Frida Developers"
        git config --global user.email "oleavr@frida.re"
        git config --global --add safe.directory $GITHUB_WORKSPACE
      shell: bash
    - name: Clean repos
      run: |
        git fetch origin --prune --prune-tags
        git submodule foreach "git clean -ffdx"
        git submodule foreach "git reset --hard HEAD"
        git submodule foreach "git fetch origin --prune --prune-tags"
      shell: bash
    - name: Check out releng
      run: git submodule update --init --recursive --depth 1 releng
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1
    - name: Configure Cloudflare credentials
      run: |
        (
          echo "defaults:"
          echo "    domain: frida.re"
          echo "    email: ${{ inputs.cloudflare-email }}"
          echo "    token: ${{ inputs.cloudflare-token }}"
        ) > ~/.cfcli.yml
      shell: bash
    - name: Set Frida environment variables
      run: |
        (
          echo "FRIDA=$GITHUB_WORKSPACE"
          echo "FRIDA_VERSION=$(releng/frida_version.py)"
        ) >> $GITHUB_ENV
      shell: bash
