name: Package artifact files as SFX
description: Downloads a specific artifact and uploads a packaged version of it
inputs:
  name:
    required: true
    description: Artifact name
runs:
  using: composite
  steps:
    - name: Download
      uses: dawidd6/action-download-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.name }}
        run_id: 3177702788
    - name: Compress
      run: |
        cd ${{ inputs.name }}
        7z a -sfx -r ..\${{ inputs.name }}.exe .
      shell: pwsh
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: release-assets
        path: ${{ inputs.name }}.exe
