name: Publish iOS packages
description: Publishes already packaged iOS debs
inputs:
  site:
    required: true
    path: Where to publish; set to either “production” or “development”
runs:
  using: composite
  steps:
    - name: Create iOS repo metadata
      run: |
        cd build
        rm -rf ios-repo-config
        mkdir ios-repo-config
        (
          echo "Origin: Cydia/Frida"
          echo "Label: frida"
          echo "Suite: stable"
          echo "Version: 1.0"
          echo "Codename: stable"
          echo "Architectures: iphoneos-arm"
          echo "Components: main"
          echo "Description: Frida for iOS"
        ) > ios-repo-config/distributions
        rm -rf ios-repo
        mkdir -p ios-repo/debs
        cd ios-repo
        (
          echo "Origin: Frida"
          echo "Label: Frida"
          echo "Suite: stable"
          echo "Version: 1.0"
          echo "Codename: ios"
          echo "Architectures: iphoneos-arm"
          echo "Components: main"
          echo "Description: Official Frida Repo"
        ) > Release
        for file in frida_${FRIDA_VERSION}_iphoneos-arm.deb; do
          cp $GITHUB_WORKSPACE/build/release-assets/$file debs/
          reprepro \
              -Vb . \
              --confdir $GITHUB_WORKSPACE/build/ios-repo-config \
              --ignore=forbiddenchar \
              includedeb \
              stable \
              debs/$file
        done
        cp dists/stable/main/binary-iphoneos-arm/Packages.gz .
        gunzip -k Packages.gz
      shell: bash
    - name: Upload iOS package and repo metadata
      run: |
        cd build/ios-repo
        case ${{ inputs.site }} in
          production)
            prefix=
            ;;
          development)
            prefix=/dev
           ;;
          *)
            echo "Invalid repo specified" > /dev/stderr
            exit 1
        esac
        aws s3 sync --delete pool/ s3://build.frida.re${prefix}/pool/
        for file in Release Packages Packages.gz; do
          aws s3 cp $file s3://build.frida.re${prefix}/
        done
        for file in Packages Packages.gz; do
          aws s3 cp $file s3://build.frida.re${prefix}/./
        done
        urls_to_invalidate=()
        for file in Release Packages Packages.gz ./Packages ./Packages.gz; do
          urls_to_invalidate+=("https://build.frida.re${prefix}/${file}")
        done
        cfcli purge ${urls_to_invalidate[@]}
      shell: bash
