name: code-style
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: psf/black@stable
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
      - run: pip install isort
      - run: isort --check-only --diff .
