from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from frida_bindgen_core.naming import to_camel_case, to_snake_case

from .model import (Enumeration, Method, Model, ObjectType, Parameter,
                    list_element_type, options_object_type, swift_ident,
                    swift_input_kind, swift_return_kind,
                    swift_return_kind_async)

_ASSETS_DIR = Path(__file__).parent / "assets"


def read_asset(name: str) -> str:
    return (_ASSETS_DIR / name).read_text(encoding="utf-8").rstrip("\n")

HEADER = """\
// Generated by frida_swift. Do not edit.
//
// This file is produced from Frida's .gir files by the shared
// frida_bindgen_core package. Regenerate via Meson rather than editing here.

internal import FridaCore
"""

# Cast helpers from a Swift scalar back to the matching GLib C scalar type,
# keyed by the gir type name.
_C_SCALAR = {
    "gint": "gint", "gint8": "gint8", "gint16": "gint16", "gint32": "gint32",
    "gint64": "gint64", "glong": "glong", "gssize": "gssize",
    "guint": "guint", "guint8": "guint8", "guint16": "guint16",
    "guint32": "guint32", "guint64": "guint64", "gulong": "gulong",
    "gsize": "gsize", "gfloat": "gfloat", "gdouble": "gdouble",
}


def generate_swift(model: Model) -> str:
    parts: List[str] = [HEADER]

    parts.append(generate_error(model))

    for enum in model.enumerations_kept:
        parts.append(generate_enum(enum))

    for otype in model.regular_object_types:
        parts.append(generate_class(otype, model))
        if otype.custom_module is not None:
            parts.append(read_asset(otype.custom_module))

    for otype in model.interface_impls:
        parts.append(generate_interface_impl(otype, model))

    return "\n\n".join(parts) + "\n"


# --- Error domain -----------------------------------------------------------

# The FridaError members carry no payload beyond a message string; a couple of
# member names collide with Swift keywords or read better renamed.
_ERROR_CASE_NAMES = {
    "protocol": "protocolViolation",
}


def generate_error(model: Model) -> str:
    domain = model.error_domain
    cases = [f"    case {_ERROR_CASE_NAMES.get(m.name, m.swift_name)}(String)"
             for m in domain.members]
    # rpcError is a Swift-only case surfaced by the Script RPC facade; it is not
    # part of the C error domain but shares this enum.
    cases.append("    case rpcError(message: String, stackTrace: String?)")

    binds = ",\n".join(f"             let .{_ERROR_CASE_NAMES.get(m.name, m.swift_name)}(message)"
                       for m in domain.members)

    return f"""\
@frozen
public enum Error: Swift.Error, Codable {{
{chr(10).join(cases)}

    public var description: String {{
        switch self {{
        case {binds.lstrip()}:
            return message

        case let .rpcError(message: message, stackTrace: stackTrace):
            if let stackTrace, !stackTrace.isEmpty {{
                return "\\(message)\\n\\n\\(stackTrace)"
            }}
            return message
        }}
    }}
}}"""


# --- Enumerations -----------------------------------------------------------


def generate_enum(enum: Enumeration) -> str:
    lines = []
    value = enum.first_value
    for member in enum.members:
        lines.append(f"    case {member.swift_name} = {value}")
        value += 1

    descs = []
    for member in enum.members:
        plain = member.swift_name.strip("`")
        descs.append(f'        case .{member.swift_name}: return "{plain}"')

    return f"""\
@frozen
public enum {enum.swift_name}: UInt32, Codable, CustomStringConvertible {{
{chr(10).join(lines)}

    public var description: String {{
        switch self {{
{chr(10).join(descs)}
        }}
    }}
}}"""


# --- Object types -----------------------------------------------------------


def generate_class(otype: ObjectType, model: Model) -> str:
    name = otype.swift_name
    signals = otype.generate_signals and otype.emitted_signals
    members: List[str] = []
    leading: List[str] = []

    if signals:
        leading.append(f"""    public var events: Events {{
        eventSource.makeStream()
    }}

    public typealias Events = AsyncStream<Event>

{generate_event_enum(otype, model)}""")

    inherited = set(otype.inherited_member_names)
    if otype.emitted_parent is not None:
        inherited.add("description")

    for method in otype.emitted_properties:
        members.append(apply_override(generate_getter(method, model), method.property_name, inherited))

    for method in otype.emitted_async_methods:
        body = read_asset(method.custom_body) if method.custom_body is not None \
            else generate_async_method(otype, method, model)
        members.append(apply_override(body, method.swift_name, inherited))

    for method in otype.emitted_custom_methods:
        members.append(apply_override(generate_custom_method(method, model), method.swift_name, inherited))

    for method in otype.emitted_sync_methods:
        members.append(apply_override(generate_sync_method(method, model), method.swift_name, inherited))

    if signals:
        for s in otype.emitted_signals:
            members.append(generate_signal_handler(otype, s, model))
        members.append("""    private func publish(_ event: Event) {
        eventSource.yield(event)
    }""")

    has_description = any(m.property_name == "description"
                          for m in otype.emitted_properties)

    if not has_description:
        members.append(apply_override(generate_description(otype, model), "description", inherited))

    if otype.extra_members is not None:
        members.append(otype.extra_members)

    if otype.custom_members is not None:
        members.append(read_asset(otype.custom_members))

    body = "\n\n".join(leading + members)
    if body:
        body += "\n\n"

    parent = otype.emitted_parent

    if parent is None:
        conformances = ["Equatable", "Hashable"] + otype.extra_conformances
        if not has_description:
            conformances.insert(0, "CustomStringConvertible")
    else:
        conformances = [parent.swift_name] + otype.extra_conformances
    if (signals or otype.sendable) and "@unchecked Sendable" not in conformances:
        conformances.insert(0, "@unchecked Sendable")

    stored = ""
    if parent is None:
        stored += "    let handle: OpaquePointer\n"
    if signals:
        stored += "    private let eventSource = AsyncEventSource<Event>()\n"

    public_init = generate_public_init(otype, model)

    init_lines = []
    if parent is None:
        init_lines.append("        self.handle = handle")
    else:
        init_lines.append("        super.init(handle: handle)")
    for s in otype.emitted_signals if signals else []:
        init_lines.append(
            f'        connectSignal(instance: self, handle: handle, '
            f'signal: "{s.name}", handler: on{to_pascal(s.event_name)})')
    if otype.custom_init is not None:
        init_lines.append(otype.custom_init)
    init_body = "\n".join(init_lines) + "\n"

    init_keyword = "init" if parent is None else "override init"

    if parent is None:
        deinit_lines = []
        if signals:
            deinit_lines.append("        eventSource.finish()")
        if otype.custom_deinit is not None:
            deinit_lines.append(otype.custom_deinit)
        deinit_lines.append("        g_object_unref(gpointer(handle))")
        deinit_body = "\n".join(deinit_lines) + "\n"
        deinit_section = f"""
    deinit {{
{deinit_body}    }}
"""
        equatable_section = f"""    public static func == (lhs: {name}, rhs: {name}) -> Bool {{
        return lhs.handle == rhs.handle
    }}

    public func hash(into hasher: inout Hasher) {{
        hasher.combine(UInt(bitPattern: handle))
    }}
"""
    else:
        deinit_section = ""
        equatable_section = ""

    if not body and not equatable_section:
        body = ""

    class_keyword = "public class" if otype.has_emitted_subclasses else "public final class"

    return f"""\
{class_keyword} {name}: {', '.join(conformances)} {{
{stored}
    {init_keyword}(handle: OpaquePointer) {{
{init_body}    }}
{public_init}{deinit_section}
{body}{equatable_section}}}"""


def generate_public_init(otype: ObjectType, model: Model) -> str:
    if otype.custom_members is not None and "init(" in read_asset(otype.custom_members):
        return ""

    if not otype.constructors:
        return ""

    primary = next((c for c in otype.constructors if c.name == "new"), otype.constructors[0])

    members = [generate_constructor_init(otype, primary, model)]
    for ctor in otype.constructors:
        if ctor is not primary:
            members.append(generate_factory_method(otype, ctor, model))
    return "".join(members)


def generate_constructor_init(otype: ObjectType, ctor, model: Model) -> str:
    if ctor.parameters:
        sig, body = marshal_constructor_call(otype, ctor, model)
        if sig is None:
            return ""
    else:
        if ctor.throws:
            return ""
        sig, setters = collect_settings(otype, model, "handle")
        body = [f"let handle = {ctor.c_identifier}()!"] + setters

    handle = "handle!" if ctor.throws else "handle"
    body.append(f"self.init(handle: {handle})")

    lines = "\n".join(f"        {line}" for line in body)
    throws_kw = " throws" if ctor.throws else ""

    return f"""
    public convenience init({', '.join(sig)}){throws_kw} {{
        Runtime.ensureInitialized()
{lines}
    }}
"""


def generate_factory_method(otype: ObjectType, ctor, model: Model) -> str:
    sig, body = marshal_constructor_call(otype, ctor, model)
    if sig is None:
        return ""

    handle = "handle!" if ctor.throws else "handle"
    body.append(f"return {otype.swift_name}(handle: {handle})")

    lines = "\n".join(f"        {line}" for line in body)
    throws_kw = " throws" if ctor.throws else ""

    return f"""
    public static func {swift_ident(ctor.name)}({', '.join(sig)}){throws_kw} -> {otype.swift_name} {{
        Runtime.ensureInitialized()
{lines}
    }}
"""


def marshal_constructor_call(otype: ObjectType, ctor, model: Model):
    sig = []
    args = []
    pre = []
    post = []
    for param in ctor.parameters:
        kind = swift_input_kind(param.type, model)
        if kind is None:
            return None, None
        call_arg, param_pre, param_post = marshal_input(param, model)
        sig.append(f"{param.swift_name}: {kind[1]}")
        args.append(call_arg)
        pre += param_pre
        post += param_post

    body = pre + acquire_handle(ctor.c_identifier, args, ctor.throws) + post
    if ctor.throws:
        body += ["if let rawError {", "    throw Marshal.takeNativeError(rawError)", "}"]
    return sig, body


def acquire_handle(new_func: str, args, throws: bool):
    if not throws:
        return [f"let handle = {new_func}({', '.join(args)})!"]
    return [
        "var rawError: UnsafeMutablePointer<GError>? = nil",
        f"let handle = {new_func}({', '.join(args + ['&rawError'])})",
    ]


def apply_override(member: str, name: str, inherited) -> str:
    if name not in inherited:
        return member
    return member.replace("    public ", "    public override ", 1)


def to_pascal(camel: str) -> str:
    return camel[0].upper() + camel[1:] if camel else camel


# --- Interface implementations ----------------------------------------------


def generate_interface_impl(otype: ObjectType, model: Model) -> str:
    name = otype.swift_name
    method = otype.implemented_method
    inputs = [
        p for p in method.parameters
        if p.type.name != "Gio.Cancellable" and p.direction.value == "in"
    ]
    param = inputs[0]
    ret = method.return_value

    vtable = method.name
    thunk = to_camel_case(method.name) + "Thunk"
    finish_thunk = to_camel_case(method.name) + "FinishThunk"
    typename = "FridaSwift" + name
    quark_key = "frida-swift-" + to_snake_case(name).replace("_", "-")

    open_method = generate_interface_open_method(method, param, ret, model)
    thunk_impl = generate_interface_thunk(name, method, param, ret, thunk, model)
    finish_impl = generate_interface_finish_thunk(finish_thunk, ret, model)

    return f"""\
open class {name} {{
    public let handle: OpaquePointer

    public init() {{
        Runtime.ensureInitialized()
        handle = {name}.makeInstance()
        {name}.register(self, on: handle)
    }}

    deinit {{
        g_object_unref(gpointer(handle))
    }}

{open_method}

    private static let quark: GQuark = "{quark_key}".withCString {{ g_quark_from_string($0) }}

    private static let gType: GType = registerType()

    private static func registerType() -> GType {{
        var info = GTypeInfo(
            class_size: guint16(MemoryLayout<GObjectClass>.stride),
            base_init: nil,
            base_finalize: nil,
            class_init: {{ _, _ in }},
            class_finalize: nil,
            class_data: nil,
            instance_size: guint16(MemoryLayout<GObject>.stride),
            n_preallocs: 0,
            instance_init: {{ _, _ in }},
            value_table: nil
        )
        let type: GType = "{typename}".withCString {{ cStr in
            g_type_register_static(g_type_from_name("GObject"), cStr, &info, GTypeFlags(rawValue: 0))
        }}
        var ifaceInfo = GInterfaceInfo(
            interface_init: {{ ifacePtr, _ in
                let iface = ifacePtr!.assumingMemoryBound(to: {otype.type_struct}.self)
                iface.pointee.{vtable} = {name}.{thunk}
                iface.pointee.{vtable}_finish = {name}.{finish_thunk}
            }},
            interface_finalize: nil,
            interface_data: nil
        )
        g_type_add_interface_static(type, {otype.get_type}(), &ifaceInfo)
        return type
    }}

    private static func makeInstance() -> OpaquePointer {{
        guard let raw = g_object_new_with_properties(gType, 0, nil, nil) else {{
            fatalError("Failed to create {typename}")
        }}
        return OpaquePointer(raw)
    }}

    private static func register(_ instance: {name}, on handle: OpaquePointer) {{
        let gobj = UnsafeMutableRawPointer(handle).assumingMemoryBound(to: GObject.self)
        g_object_set_qdata_full(gobj, quark, Unmanaged.passRetained(Box(instance)).toOpaque(), {{ data in
            if let data {{
                Unmanaged<Box>.fromOpaque(data).release()
            }}
        }})
    }}

    private static func getBox(from ptr: OpaquePointer) -> Box {{
        let gobj = UnsafeMutableRawPointer(ptr).assumingMemoryBound(to: GObject.self)
        return Unmanaged<Box>.fromOpaque(g_object_get_qdata(gobj, quark)!).takeUnretainedValue()
    }}

    private static func makeError(from error: Swift.Error) -> UnsafeMutablePointer<GError>? {{
        String(describing: error).withCString {{ cStr in
            g_error_new_literal(frida_error_quark(), gint(FRIDA_ERROR_INVALID_OPERATION.rawValue), cStr)
        }}
    }}

{thunk_impl}

{finish_impl}

    private final class Box {{
        let instance: {name}
        init(_ instance: {name}) {{
            self.instance = instance
        }}
    }}
}}"""


def interface_swift_type(type, model, nullable: bool) -> str:
    if type.name == "utf8":
        return "String"
    obj = model.swift_class_for(type.name)
    return obj.swift_name + ("?" if nullable else "")


def generate_interface_open_method(method, param, ret, model) -> str:
    param_type = interface_swift_type(param.type, model, param.nullable)
    ret_type = interface_swift_type(ret.type, model, ret.nullable)
    return (f"    open func {method.swift_name}({param.swift_name}: {param_type}) "
            f"async throws -> {ret_type} {{\n"
            f'        fatalError("Override {method.swift_name} in your {method.object_type.swift_name} subclass")\n'
            f"    }}")


def generate_interface_thunk(name, method, param, ret, thunk, model) -> str:
    c_param_type, marshal_in = interface_input_marshal(param, model)
    call_arg = f"{param.swift_name}: value"
    return_body = interface_return_marshal(ret, model)
    return f"""\
    private static let {thunk}: @convention(c) (
        OpaquePointer?,
        {c_param_type},
        UnsafeMutablePointer<GCancellable>?,
        GAsyncReadyCallback?,
        gpointer?
    ) -> Void = {{ selfPtr, rawValue, cancellable, callback, userData in
        let box = {name}.getBox(from: selfPtr!)
        {marshal_in}
        guard let task = g_task_new(UnsafeMutableRawPointer(selfPtr), cancellable, callback, userData) else {{
            return
        }}
        Task.detached {{
            do {{
                let result = try await box.instance.{method.swift_name}({call_arg})
{return_body}
            }} catch {{
                g_task_return_error(task, {name}.makeError(from: error))
            }}
            g_object_unref(gpointer(task))
        }}
    }}"""


def interface_input_marshal(param, model):
    if param.type.name == "utf8":
        return ("UnsafePointer<CChar>?",
                "let value = rawValue.map { String(cString: $0) } ?? \"\"")
    wrapper = model.swift_class_for(param.type.name).swift_name
    return ("OpaquePointer?", f"let value = {wrapper}(handle: rawValue!)")


def interface_return_marshal(ret, model) -> str:
    if ret.type.name == "utf8":
        return ("                result.withCString { cStr in\n"
                "                    g_task_return_pointer(task, UnsafeMutableRawPointer(g_strdup(cStr)), "
                "{ ptr in if let ptr { g_free(ptr) } })\n"
                "                }")
    ref = "                    g_object_ref(gpointer(result.handle))\n"
    put = ("                    g_task_return_pointer(task, UnsafeMutableRawPointer(result.handle), "
           "{ ptr in if let ptr { g_object_unref(ptr) } })")
    if ret.nullable:
        return (f"                if let result {{\n{ref}{put}\n"
                f"                }} else {{\n"
                f"                    g_task_return_pointer(task, nil, nil)\n"
                f"                }}")
    return ref + put


def generate_interface_finish_thunk(finish_thunk, ret, model) -> str:
    if ret.type.name == "utf8":
        ret_type = "UnsafeMutablePointer<CChar>?"
        body = "        return g_task_propagate_pointer(resultPtr, errorOut)?.assumingMemoryBound(to: CChar.self)"
    else:
        ret_type = "OpaquePointer?"
        body = "        return g_task_propagate_pointer(resultPtr, errorOut).map { OpaquePointer($0) }"
    return f"""\
    private static let {finish_thunk}: @convention(c) (
        OpaquePointer?,
        OpaquePointer?,
        UnsafeMutablePointer<UnsafeMutablePointer<GError>?>?
    ) -> {ret_type} = {{ _, resultPtr, errorOut in
{body}
    }}"""


def generate_description(otype: ObjectType, model: Model) -> str:
    fields = []
    for method in otype.emitted_properties:
        kind, _ = swift_return_kind(method.return_value.type, model)
        prop = method.property_name
        if kind == "string" and not method.return_value.nullable:
            fields.append(f'{prop}: \\"\\({prop})\\"')
        elif kind in ("scalar", "enum"):
            fields.append(f"{prop}: \\({prop})")
    summary = ", ".join(fields)
    return (f"    public var description: String {{\n"
            f'        return "Frida.{otype.swift_name}({summary})"\n'
            f"    }}")


# --- Signals / events -------------------------------------------------------


def generate_event_enum(otype: ObjectType, model: Model) -> str:
    cases = []
    for s in otype.emitted_signals:
        payload = s.event_payload
        if not payload:
            cases.append(f"        case {s.event_name}")
            continue
        index_of = {p.name: i for i, p in enumerate(s.parameters)}
        parts = []
        for label, param in payload:
            transform = s.transform.get(index_of[param.name])
            swift_type = transform[0] if transform is not None else signal_param_kind(param, model)[1]
            parts.append(f"{label}: {swift_type}" if label else swift_type)
        cases.append(f"        case {s.event_name}({', '.join(parts)})")
    for case in otype.event_cases:
        cases.append(f"        case {case}")
    return "    @frozen\n    public enum Event {\n" + "\n".join(cases) + "\n    }"


def signal_param_kind(param: Parameter, model: Model):
    """Return (c_closure_type, swift_type) for a signal parameter."""
    t = param.type
    n = t.name
    nn = param.nullable
    if n == "utf8":
        return ("UnsafePointer<gchar>?" if nn else "UnsafePointer<gchar>",
                "String?" if nn else "String")
    if n == "GLib.Bytes":
        return ("OpaquePointer?" if nn else "OpaquePointer",
                "[UInt8]?" if nn else "[UInt8]")
    if n == "guint":
        return ("guint", "UInt")
    if n in ("gint", "gint32"):
        return ("gint", "Int")
    if n == "gdouble":
        return ("gdouble", "Double")
    enum = model.enumerations.get(n.split(".")[-1])
    if enum is not None and not enum.drop:
        return ("Int", enum.swift_name)
    obj = model.swift_class_for(n)
    if obj is not None and obj.emit:
        return ("OpaquePointer?" if nn else "OpaquePointer",
                obj.swift_name + ("?" if nn else ""))
    raise AssertionError(f"unsupported signal param: {n}")


def generate_getter(method: Method, model: Model) -> str:
    rv = method.return_value
    kind, swift_type = swift_return_kind(rv.type, model)
    call = f"{method.c_identifier}(handle)"
    nullable = rv.nullable

    if kind == "scalar" and swift_type == "Bool":
        body = f"        return {call} != 0"
    elif kind == "scalar":
        body = f"        return {swift_type}({call})"
    elif kind == "enum":
        body = f"        return {swift_type}(rawValue: numericCast({call}.rawValue))!"
    elif kind == "string":
        if nullable:
            swift_type += "?"
            body = (f"        if let raw = {call} {{\n"
                    f"            return String(cString: raw)\n"
                    f"        }}\n"
                    f"        return nil")
        else:
            body = f"        return String(cString: {call})"
    elif kind == "bytes":
        swift_type += "?"
        body = f"        return Marshal.arrayFromBytes({call})"
    elif kind == "strv":
        custom = method.customizations
        swift_type = custom.swift_type if custom and custom.swift_type else "[String]?"
        converter = custom.strv_converter if custom and custom.strv_converter else "arrayFromStrv"
        body = (f"        guard let raw = {method.c_identifier}(handle, nil) else {{\n"
                f"            return nil\n"
                f"        }}\n"
                f"        return Marshal.{converter}(raw)")
    elif kind == "vardict":
        body = f"        return Marshal.dictionaryFromParametersDict({call})"
    elif kind == "object":
        if nullable:
            swift_type += "?"
            body = (f"        guard let raw = {call} else {{\n"
                    f"            return nil\n"
                    f"        }}\n"
                    f"        g_object_ref(gpointer(raw))\n"
                    f"        return {swift_type.rstrip('?')}(handle: raw)")
        else:
            body = (f"        let raw = {call}!\n"
                    f"        g_object_ref(gpointer(raw))\n"
                    f"        return {swift_type}(handle: raw)")
    else:
        raise AssertionError(kind)

    return (f"    public var {method.property_name}: {swift_type} {{\n"
            f"{body}\n"
            f"    }}")


def generate_async_method(otype: ObjectType, method: Method, model: Model) -> str:
    rv_type = method.return_value.type if method.return_value else None
    kind, swift_type = swift_return_kind_async(rv_type, model)
    nullable = method.return_value.nullable if method.return_value else False
    if kind == "object" and nullable:
        swift_ret = swift_type + "?"
    elif kind == "string" and nullable:
        swift_ret = swift_type + "?"
    else:
        swift_ret = swift_type

    params = method.swift_input_parameters

    sig_parts: List[str] = []
    pre: List[str] = []
    call_args: List[str] = ["self.handle"]
    post: List[str] = []
    for p in params:
        if p.type.is_frida_options:
            option_sig, option_pre, option_post = expand_options(p, model)
            sig_parts.extend(option_sig)
            pre.extend(option_pre)
            post.extend(option_post)
            call_args.append("options")
            continue
        sig_parts.append(f"{p.swift_name}: {swift_input_kind(p.type, model)[1]}")
        arg, pre_lines, post_lines = marshal_input(p, model)
        call_args.append(arg)
        pre.extend(pre_lines)
        post.extend(post_lines)
    call_args.append("op.cancellable")

    sig_params = ", ".join(sig_parts)

    completion = generate_completion(method, kind, swift_ret, model)

    pre_block = "".join(f"            {line}\n" for line in pre)
    post_block = "".join(f"            {line}\n" for line in post)

    inner_args = ", ".join(call_args)

    return f"""\
    public func {method.swift_name}({sig_params}) async throws -> {swift_ret} {{
        return try await fridaAsync({swift_ret}.self) {{ op in
{pre_block}            {method.c_identifier}({inner_args}, {{ sourcePtr, asyncResultPtr, userData in
{completion}
            }}, op.userData)
{post_block}        }}
    }}"""


def generate_custom_method(method: Method, model: Model) -> str:
    logic = method.custom_logic
    pre: List[str] = [logic]
    post: List[str] = []
    call_args: List[str] = ["self.handle"]
    for p in method.swift_input_parameters:
        supplied_by_logic = f"let {p.name} " in logic
        if supplied_by_logic:
            call_args.append(p.name)
            continue
        arg, pre_lines, post_lines = marshal_input(p, model)
        call_args.append(arg)
        pre.extend(pre_lines)
        post.extend(post_lines)

    statements = pre + [f"{method.c_identifier}({', '.join(call_args)})"] + post
    body = "".join(f"        {line}\n" for line in statements)
    return f"""\
    public func {method.swift_name}({', '.join(method.param_typings)}) {{
{body}    }}"""


def generate_sync_method(method: Method, model: Model) -> str:
    sig_parts: List[str] = []
    pre: List[str] = []
    call_args: List[str] = ["handle"]
    post: List[str] = []
    for p in method.swift_input_parameters:
        sig_parts.append(f"{p.swift_name}: {swift_input_kind(p.type, model)[1]}")
        arg, pre_lines, post_lines = marshal_input(p, model)
        call_args.append(arg)
        pre.extend(pre_lines)
        post.extend(post_lines)

    rv = method.return_value
    returns_strv = rv is not None and swift_return_kind(rv.type, model)[0] == "strv"

    lines = list(pre)
    if returns_strv:
        call = f"{method.c_identifier}({', '.join(call_args + ['nil'])})"
        lines += [f"guard let raw = {call} else {{", "    return []", "}",
                  "return Marshal.arrayFromStrv(raw)"]
        ret_sig = " -> [String]"
    elif method.throws:
        lines.append("var rawError: UnsafeMutablePointer<GError>? = nil")
        lines.append(f"{method.c_identifier}({', '.join(call_args + ['&rawError'])})")
        lines.extend(post)
        lines += ["if let rawError {", "    throw Marshal.takeNativeError(rawError)", "}"]
        ret_sig = ""
    else:
        lines.append(f"{method.c_identifier}({', '.join(call_args)})")
        lines.extend(post)
        ret_sig = ""

    body = "".join(f"        {line}\n" for line in lines)
    throws_kw = " throws" if method.throws else ""
    sig = ", ".join(method.param_typings if method.param_typings is not None else sig_parts)
    return f"""\
    public func {method.swift_name}({sig}){throws_kw}{ret_sig} {{
{body}    }}"""


def expand_options(param: Parameter, model: Model):
    """Expand a Frida*Options parameter into inline default-nil labelled args.

    Returns (signature_fragments, pre_lines, post_lines). The pre_lines build a
    local `options` GObject from whichever setters were supplied; post_lines
    unref it. Setters whose value types are not marshalable here (TLS
    certificates, Relay objects, aux vardicts) are omitted and remain the
    province of a later hand-written facade.
    """
    from .model import options_object_type

    otype = options_object_type(param.type, model)
    new_func = otype.constructors[0].c_identifier

    sig: List[str] = []
    pre: List[str] = [f"let options = {new_func}()!"]
    sig, setter_lines = collect_settings(otype, model, "options",
                                         stop_at_parent=lambda t: t.is_frida_options)
    pre.extend(setter_lines)

    post = ["g_object_unref(gpointer(options))"]
    return sig, pre, post



def collect_settings(otype, model: Model, target: str, stop_at_parent=None):
    sig: List[str] = []
    lines: List[str] = []

    seen = set()
    current = otype
    while current is not None:
        for setter in current.methods:
            if setter.name in seen:
                continue
            seen.add(setter.name)
            entry = classify_option_setter(setter, model, target)
            if entry is None:
                continue
            arg_name, swift_type, build = entry
            sig.append(f"{arg_name}: {swift_type} = nil")
            lines.extend(build)
        parent = current.parent
        if parent is None or (stop_at_parent is not None and not stop_at_parent(parent)):
            break
        current = parent

    return sig, lines


def classify_option_setter(setter: Method, model: Model, target: str = "options"):
    """Return (arg_name, swift_type, build_lines) for a supported option setter."""
    from frida_bindgen_core.naming import to_camel_case
    name = setter.name
    params = setter.input_parameters

    if name.startswith("set_"):
        prop = name[len("set_"):]
        arg = swift_ident(prop)
        if params and params[0].type.name == "utf8[]":
            custom = setter.customizations
            swift_type = custom.swift_type if custom and custom.swift_type else "[String]?"
            converter = custom.strv_converter if custom and custom.strv_converter else "strvFromArray"
            raw = f"raw{prop.title().replace('_', '')}"
            build = [
                f"let ({raw}, {raw}Length) = Marshal.{converter}({arg})",
                f"if let {raw} = {raw} {{",
                f"    {setter.c_identifier}({target}, {raw}, {raw}Length)",
                f"    g_strfreev({raw})",
                f"}}",
            ]
            return arg, swift_type, build
        if len(params) != 1:
            return None
        return _scalar_setter(setter, arg, params[0], model, target)

    if name.startswith("select_") or name.startswith("add_"):
        prop = name.split("_", 1)[1]
        arg = swift_ident(prop) + "s"
        if len(params) == 2 and params[0].type.name == "utf8":
            return _mapping_setter(setter, arg, params[1], model, target)
        if len(params) != 1:
            return None
        return _adder_setter(setter, arg, params[0], model, target)

    return None



def _mapping_setter(setter, arg, param, model, target="options"):
    kind = swift_input_kind(param.type, model)
    if kind is None:
        return None
    tag, swift_type = kind
    call = setter.c_identifier
    if tag == "string":
        return arg, "[String: String]?", [
            f"for (key, element) in {arg} ?? [:] {{", f"    {call}({target}, key, element)", f"}}"]
    if tag == "scalar" and swift_type != "Bool":
        cname = _C_SCALAR[param.type.name]
        return arg, f"[String: {swift_type}]?", [
            f"for (key, element) in {arg} ?? [:] {{", f"    {call}({target}, key, {cname}(element))", f"}}"]
    if tag == "object":
        return arg, f"[String: {swift_type}]?", [
            f"for (key, element) in {arg} ?? [:] {{", f"    {call}({target}, key, element.handle)", f"}}"]
    return None


def _scalar_setter(setter, arg, param, model, target="options"):
    kind = swift_input_kind(param.type, model)
    if kind is None:
        return None
    call = setter.c_identifier
    tag, swift_type = kind
    if tag == "string":
        return arg, "String?", [f"if let {arg} = {arg} {{", f"    {call}({target}, {arg})", f"}}"]
    if tag == "bytes":
        raw = f"raw{arg[0].upper()}{arg[1:]}"
        return arg, "[UInt8]?", [
            f"let {raw} = Marshal.bytesFromArray({arg})",
            f"if let {raw} = {raw} {{",
            f"    {call}({target}, {raw})",
            f"    g_bytes_unref({raw})",
            f"}}",
        ]
    if tag == "scalar":
        if swift_type == "Bool":
            return arg, "Bool?", [
                f"if let {arg} = {arg} {{",
                f"    {call}({target}, {arg} ? gboolean(1) : gboolean(0))",
                f"}}",
            ]
        cname = _C_SCALAR[param.type.name]
        return arg, f"{swift_type}?", [
            f"if let {arg} = {arg} {{", f"    {call}({target}, {cname}({arg}))", f"}}"]
    if tag == "enum":
        cenum = param.type.c.replace("*", "").strip()
        return arg, f"{swift_type}?", [
            f"if let {arg} = {arg} {{",
            f"    {call}({target}, {cenum}(numericCast({arg}.rawValue)))",
            f"}}",
        ]
    if tag == "object":
        return arg, f"{swift_type}?", [
            f"if let {arg} = {arg} {{", f"    {call}({target}, {arg}.handle)", f"}}"]
    return None


def _adder_setter(setter, arg, param, model, target="options"):
    kind = swift_input_kind(param.type, model)
    if kind is None:
        return None
    tag, swift_type = kind
    call = setter.c_identifier
    if tag == "string":
        elem = "element"
        return arg, "[String]?", [
            f"for {elem} in {arg} ?? [] {{", f"    {call}({target}, {elem})", f"}}"]
    if tag == "scalar" and swift_type != "Bool":
        cname = _C_SCALAR[param.type.name]
        return arg, f"[{swift_type}]?", [
            f"for element in {arg} ?? [] {{", f"    {call}({target}, {cname}(element))", f"}}"]
    if tag == "enum":
        cenum = param.type.c.replace("*", "").strip()
        return arg, f"[{swift_type}]?", [
            f"for element in {arg} ?? [] {{",
            f"    {call}({target}, {cenum}(numericCast(element.rawValue)))",
            f"}}",
        ]
    if tag == "object":
        return arg, f"[{swift_type}]?", [
            f"for element in {arg} ?? [] {{", f"    {call}({target}, element.handle)", f"}}"]
    return None


def marshal_input(param: Parameter, model: Model):
    """Return (call_arg, pre_lines, post_lines) for an input parameter."""
    name = param.swift_name
    kind, _ = swift_input_kind(param.type, model)
    if kind == "string":
        return name, [], []
    if kind == "scalar":
        cname = _C_SCALAR[param.type.name]
        return f"{cname}({name})", [], []
    if kind == "enum":
        cenum = param.type.c.replace("*", "").strip()
        return f"{cenum}(numericCast({name}.rawValue))", [], []
    if kind == "bytes":
        raw = f"raw{name[0].upper()}{name[1:]}"
        return raw, [f"let {raw} = Marshal.bytesFromArray({name})"], [f"g_bytes_unref({raw})"]
    if kind == "variant":
        raw = f"raw{name[0].upper()}{name[1:]}"
        return (raw,
                [f"let {raw} = g_variant_ref_sink(Marshal.variantFromValue({name}))"],
                [f"g_variant_unref({raw})"])
    if kind == "object":
        return f"{name}.handle", [], []
    raise AssertionError(kind)


def generate_completion(method: Method, kind: str, swift_ret: str, model: Model) -> str:
    finish = method.finish_c_identifier
    op_line = f"                let op = InternalOp<{swift_ret}>.takeRetained(from: userData!)"
    err_decl = "                var rawError: UnsafeMutablePointer<GError>? = nil"

    if kind == "void":
        finish_call = f"                {finish}(OpaquePointer(sourcePtr), asyncResultPtr, &rawError)"
    else:
        finish_call = f"                let rawResult = {finish}(OpaquePointer(sourcePtr), asyncResultPtr, &rawError)"

    err_check = ("                if let rawError {\n"
                 "                    op.resumeFailure(Marshal.takeNativeError(rawError))\n"
                 "                    return\n"
                 "                }")

    success = generate_success(method, kind, swift_ret, model)

    return "\n\n".join([op_line, "\n".join([err_decl, finish_call]), err_check, success])


def generate_success(method: Method, kind: str, swift_ret: str, model: Model) -> str:
    nullable = method.return_value.nullable if method.return_value else False
    if kind == "void":
        return "                op.resumeSuccess(())"
    if kind == "scalar":
        if swift_ret == "Bool":
            return "                op.resumeSuccess(rawResult != 0)"
        return f"                op.resumeSuccess({swift_ret}(rawResult))"
    if kind == "enum":
        base = swift_ret.rstrip("?")
        return f"                op.resumeSuccess({base}(rawValue: numericCast(rawResult.rawValue))!)"
    if kind == "string":
        if nullable:
            return ("                op.resumeSuccess(rawResult != nil ? String(cString: rawResult!) : nil)")
        return "                op.resumeSuccess(String(cString: rawResult!))"
    if kind == "bytes":
        return ("                op.resumeSuccess(Marshal.arrayFromBytes(rawResult)!)\n"
                "                g_bytes_unref(rawResult)")
    if kind == "vardict":
        return ("                let parameters = Marshal.dictionaryFromParametersDict(rawResult!)\n"
                "                g_hash_table_unref(rawResult!)\n"
                "                op.resumeSuccess(parameters)")
    if kind == "object":
        base = swift_ret.rstrip("?")
        if nullable:
            return (f"                op.resumeSuccess(rawResult != nil ? {base}(handle: rawResult!) : nil)")
        return f"                op.resumeSuccess({base}(handle: rawResult!))"
    if kind == "giostream":
        return "                op.resumeSuccess(GLib.IOStream(handle: rawResult!))"
    if kind == "variant":
        return ("                let value = Marshal.valueFromVariant(rawResult!)\n"
                "                g_variant_unref(rawResult!)\n"
                "                op.resumeSuccess(value)")
    if kind == "list":
        return generate_list_success(method, swift_ret, model)
    raise AssertionError(kind)


def generate_list_success(method: Method, swift_ret: str, model: Model) -> str:
    list_obj = model.swift_class_for(method.return_value.type.name)
    element = list_element_type(list_obj, model)
    prefix = "frida_" + to_snake_case(element.name)
    elem_swift = element.swift_name
    return (f"                var items: {swift_ret} = []\n"
            f"                let n = {prefix}_list_size(rawResult)\n"
            f"                for i in 0..<n {{\n"
            f"                    items.append({elem_swift}(handle: {prefix}_list_get(rawResult, i)))\n"
            f"                }}\n"
            f"                g_object_unref(gpointer(rawResult))\n"
            f"                op.resumeSuccess(items)")


# --- Signal handlers --------------------------------------------------------


def generate_signal_handler(otype: ObjectType, signal, model: Model) -> str:
    name = otype.swift_name
    handler = "on" + to_pascal(signal.event_name)

    args = [(param, f"arg{i}") for i, param in enumerate(signal.parameters)]
    closure_params = ["_"] + [var for _, var in args] + ["userData"]

    sig_types = (["OpaquePointer"]
                 + [signal_param_kind(param, model)[0] for param in signal.parameters]
                 + ["gpointer"])
    sig = f"@convention(c) ({', '.join(sig_types)}) -> Void"

    lines = [
        f"        let connection = Unmanaged<SignalConnection<{name}>>"
        f".fromOpaque(userData).takeUnretainedValue()",
        "        guard let instance = connection.instance else { return }",
    ]

    var_by_param = {}
    for i, (param, var) in enumerate(args):
        expr_lines, local = marshal_signal_param(param, var, model)
        lines.extend("        " + l for l in expr_lines)
        transform = signal.transform.get(i)
        if transform is not None:
            _, converter = transform
            parsed = f"{param.swift_name}Parsed"
            lines.append(f"        guard let {parsed} = try? {converter}({local}) else {{ return }}")
            local = parsed
        var_by_param[param.name] = local

    payload = signal.event_payload
    if not payload:
        arg_str = ""
    else:
        parts = []
        for label, param in payload:
            v = var_by_param[param.name]
            parts.append(f"{label}: {v}" if label else v)
        arg_str = "(" + ", ".join(parts) + ")"

    if signal.terminal:
        lines.append(f"        instance.eventSource.finish(replayLast: .{signal.event_name}{arg_str})")
    else:
        lines.append(f"        instance.publish(.{signal.event_name}{arg_str})")

    body = "\n".join(lines)
    return (f"    private let {handler}: {sig} = "
            f"{{ {', '.join(closure_params)} in\n{body}\n    }}")


def marshal_signal_param(param: Parameter, var: str, model: Model):
    n = param.type.name
    nn = param.nullable
    local = f"{param.swift_name}Value"
    if n == "utf8":
        if nn:
            return ([f"let {local} = {var} != nil ? String(cString: {var}!) : nil"], local)
        return ([f"let {local} = String(cString: {var})"], local)
    if n == "GLib.Bytes":
        suffix = "" if nn else "!"
        return ([f"let {local} = Marshal.arrayFromBytes({var}){suffix}"], local)
    if n == "guint":
        return ([], f"UInt({var})")
    if n in ("gint", "gint32"):
        return ([], f"Int({var})")
    if n == "gdouble":
        return ([], f"Double({var})")
    enum = model.enumerations.get(n.split(".")[-1])
    if enum is not None and not enum.drop:
        return ([], f"{enum.swift_name}(rawValue: numericCast({var}))!")
    obj = model.swift_class_for(n)
    if nn:
        lines = [
            f"var {local}: {obj.swift_name}? = nil",
            f"if let {var} = {var} {{",
            f"    g_object_ref(gpointer({var}))",
            f"    {local} = {obj.swift_name}(handle: {var})",
            f"}}",
        ]
        return (lines, local)
    lines = [
        f"g_object_ref(gpointer({var}))",
        f"let {local} = {obj.swift_name}(handle: {var})",
    ]
    return (lines, local)
