"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

plist = dict(
    CFBundleShortVersionString="CpuShark v1",
    CFBundleIconFile="CpuShark.icns",
    CFBundleGetInfoString="CpuShark v1",
    CFBundleIdentifier="com.tillitech.CpuShark",
    CFBundleDocumentTypes=[],
    CFBundleName="CpuShark",
)

setup(
    app=["CpuShark.py"],
    data_files=["MainMenu.xib", "MainWindow.xib"],
    options={"py2app": {"plist": plist}},
    setup_requires=["py2app"],
)
