name: Set up macOS environment
description: Set up everything needed to build and release things on macOS
inputs:
  certificates-p12:
    required: true
    description: The certificates to use for codesigning, as a base64-encoded .p12
  certificates-password:
    required: true
    description: The password for the .p12
  keychain-password:
    required: true
    description: The keychain password to use
  aws-access-key-id:
    required: true
    description: The aws-access-key-id used to authenticate with AWS
  aws-secret-access-key:
    required: true
    description: The aws-secret-access-key used to authenticate with AWS
  cloudflare-email:
    required: true
    description: The email used to authenticate with Cloudflare
  cloudflare-token:
    required: true
    description: The token used to authenticate with Cloudflare
runs:
  using: composite
  steps:
    - name: Install the Apple certificates
      env:
        CERTIFICATES_P12: ${{ inputs.certificates-p12 }}
        CERTIFICATES_PASSWORD: ${{ inputs.certificates-password }}
        KEYCHAIN_PASSWORD: ${{ inputs.keychain-password }}
      run: |
        CERTIFICATE_PATH=$RUNNER_TEMP/apple-certificates.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/frida-signing.keychain-db
        echo -n "$CERTIFICATES_P12" | base64 --decode --output $CERTIFICATE_PATH
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security import $CERTIFICATE_PATH -P "$CERTIFICATES_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        rm $CERTIFICATE_PATH
        (
          MACOS_CERTID=$(security find-identity -v -p codesigning | grep "Developer ID Application: " | awk '{ print $2 }')
          IOS_CERTID=$(security find-identity -v -p codesigning | grep "Apple Development: " | awk '{ print $2 }')
          echo MACOS_CERTID=$MACOS_CERTID
          echo IOS_CERTID=$IOS_CERTID
          echo WATCHOS_CERTID=$IOS_CERTID
          echo TVOS_CERTID=$IOS_CERTID
        ) >> $GITHUB_ENV
      shell: bash
    - name: Configure git
      run: |
        git config --global user.name "Frida Developers"
        git config --global user.email "oleavr@frida.re"
      shell: bash
    - name: Clean repos
      run: |
        git fetch origin --prune --prune-tags
        git submodule foreach "git clean -ffdx"
        git submodule foreach "git reset --hard HEAD"
        git submodule foreach "git fetch origin --prune --prune-tags"
      shell: bash
    - name: Check out releng
      run: git submodule update --init --recursive --depth 1 releng
      shell: bash
    - name: Configure AWS credentials (x64)
      if: runner.arch == 'X64'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1
    - name: Configure AWS credentials (arm64)
      if: runner.arch == 'ARM64'
      run: |
        mkdir -p ~/.aws
        (
          echo "[default]"
          echo "region = us-east-1"
        ) > ~/.aws/config
        (
          echo "[default]"
          echo "aws_access_key_id = ${{ inputs.aws-access-key-id }}"
          echo "aws_secret_access_key = ${{ inputs.aws-secret-access-key }}"
        ) > ~/.aws/credentials
      shell: bash
    - name: Configure Cloudflare credentials
      run: |
        (
          echo "defaults:"
          echo "    domain: frida.re"
          echo "    email: ${{ inputs.cloudflare-email }}"
          echo "    token: ${{ inputs.cloudflare-token }}"
        ) > ~/.cfcli.yml
      shell: bash
    - name: Install Python
      if: runner.arch == 'X64'
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install cloudflare-cli
      if: runner.arch == 'X64'
      run: npm install -g cloudflare-cli
      shell: bash
    - name: Set Frida environment variables
      run: |
        (
          echo "FRIDA=$GITHUB_WORKSPACE"
          echo "FRIDA_VERSION=$(releng/frida_version.py)"
        ) >> $GITHUB_ENV
      shell: bash
