name: CI

on: push

env:
  FRIDA_COMPILER_MOD: subprojects/frida-core/src/compiler/go.mod
  ANDROID_NDK_VERSION: r29

jobs:
  toolchain-windows:
    strategy:
      matrix:
        arch: [x86, arm64]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
      - name: Set up environment
        uses: ./.github/actions/setup-windows-env
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          cloudflare-email: ${{ secrets.CF_EMAIL }}
          cloudflare-token: ${{ secrets.CF_TOKEN }}
      - name: Roll toolchain
        run: python releng\deps.py roll toolchain windows-${{ matrix.arch }}

  sdk-windows:
    needs: toolchain-windows
    strategy:
      matrix:
        arch: [x86, x86_64, arm64]
        config: [md, mdd, mt, mtd]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
      - name: Set up environment
        uses: ./.github/actions/setup-windows-env
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          cloudflare-email: ${{ secrets.CF_EMAIL }}
          cloudflare-token: ${{ secrets.CF_TOKEN }}
      - name: Roll SDK
        run: python releng\deps.py roll sdk windows-${{ matrix.arch }}-${{ matrix.config }} --activate


  frida-windows-intel:
    needs: sdk-windows
    strategy:
      matrix:
        include:
          - { arch: x86,    sys: MINGW32,    pkg: 'mingw-w64-i686-gcc'            }
          - { arch: x86_64, sys: MINGW64,    pkg: 'mingw-w64-x86_64-gcc'          }
      fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up environment
        uses: ./.github/actions/setup-windows-env
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          cloudflare-email: ${{ secrets.CF_EMAIL }}
          cloudflare-token: ${{ secrets.CF_TOKEN }}
          architecture: ${{ matrix.arch == 'x86_64' && 'x64' || matrix.arch }}
      - name: Install MinGW toolchain for cgo support
        id: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: ${{ matrix.pkg }}
      - name: Grab frida-core
        run: python tools/ensure-submodules.py frida-core
      - name: Install Go toolchain
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.FRIDA_COMPILER_MOD }}
          cache-dependency-path: ${{ env.FRIDA_COMPILER_MOD }}
      - name: Install Qt
        if: matrix.arch == 'x86_64'
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.0'
          cache: true
          setup-python: false
      - name: Configure
        run: >-
          .\configure
          --prefix=$Env:FRIDA_PREFIX
          --host=windows-${{ matrix.arch }}
          --enable-gadget
          --enable-server
          --enable-portal
          --enable-inject
          --
          "-Dfrida_qml=auto"
          "-Dfrida-gum:devkits=gum,gumjs"
          "-Dfrida-core:compiler_backend=enabled"
          "-Dfrida-core:devkits=core"
        env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
      - name: Compile
        run: .\make
      - name: Install
        run: .\make install
      - name: Upload components needed for emulation on arm64
        if: matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v7
        with:
          name: frida-core-emulation-windows
          path: |
            build/subprojects/frida-core/src/frida-helper.exe
            build/subprojects/frida-core/lib/agent/frida-agent.dll
            build/subprojects/frida-core/compat/frida-helper.exe
            build/subprojects/frida-core/compat/frida-agent.dll
      - name: Upload Gum devkit
        uses: actions/upload-artifact@v7
        with:
          name: frida-gum-devkit-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/lib/frida-1.0/devkits/gum/
      - name: Upload GumJS devkit
        uses: actions/upload-artifact@v7
        with:
          name: frida-gumjs-devkit-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/lib/frida-1.0/devkits/gumjs/
      - name: Upload Core devkit
        uses: actions/upload-artifact@v7
        with:
          name: frida-core-devkit-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/lib/frida-1.0/devkits/core/
      - name: Upload frida-server
        uses: actions/upload-artifact@v7
        with:
          name: frida-server-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/bin/frida-server.exe
      - name: Upload frida-portal
        uses: actions/upload-artifact@v7
        with:
          name: frida-portal-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/bin/frida-portal.exe
      - name: Upload frida-inject
        uses: actions/upload-artifact@v7
        with:
          name: frida-inject-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/bin/frida-inject.exe
      - name: Upload 32-bit frida-gadget
        if: matrix.arch != 'x86_64'
        uses: actions/upload-artifact@v7
        with:
          name: frida-gadget-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/lib/frida-1.0/x86/frida-gadget.dll
      - name: Upload 64-bit frida-gadget
        if: matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v7
        with:
          name: frida-gadget-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/lib/frida-1.0/x86_64/frida-gadget.dll
      - name: Package Python bindings
        run: |
          $Env:FRIDA_EXTENSION = "$Env:FRIDA_PREFIX\lib\site-packages\frida\_frida.pyd"
          cd subprojects\frida-python
          pip wheel -w "$Env:FRIDA_PREFIX\wheels" --no-deps .
      - name: Upload Python bindings
        uses: actions/upload-artifact@v7
        with:
          name: frida-python-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/wheels/*.whl
      - name: Build Node.js bindings
        if: matrix.arch == 'x86_64'
        run: |
          $installdir = "$Env:FRIDA_PREFIX\prebuilds"
          $Env:FRIDA_DEPS = "$pwd\deps"
          $Env:PKG_CONFIG_PATH = "$Env:FRIDA_PREFIX\lib\pkgconfig"
          function Run {
            param(
              [Parameter(Mandatory)]
              [string] $FilePath,
              [Parameter(ValueFromRemainingArguments = $true)]
              [string[]] $Argv
            )
            $p = Start-Process -FilePath $FilePath -ArgumentList $Argv -NoNewWindow -Wait -PassThru
            if ($p.ExitCode -ne 0) {
              throw "'$FilePath $($Argv -join ' ')' failed with exit status $($p.ExitCode)"
            }
          }
          Run python .\tools\ensure-submodules.py frida-node
          cd subprojects\frida-node
          Run npm.cmd version $Env:FRIDA_VERSION
          Run .\configure `
              --prefix=$Env:FRIDA_PREFIX `
              --host=windows-${{ matrix.arch }}
          Run .\make prebuild
          New-Item -ItemType Directory -Path $installdir
          Copy-Item .\build\*.tar.gz -Destination $installdir
      - name: Upload Node.js bindings
        if: matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v7
        with:
          name: frida-node-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/prebuilds/*.tar.gz
      - name: Build .NET bindings
        run: >-
          Remove-Item build -Recurse
          && .\configure
          --prefix=$Env:FRIDA_PREFIX
          --host=windows-${{ matrix.arch }}-md
          --enable-frida-clr
          --disable-frida-python
          --disable-frida-tools
          --
          "-Dfrida-core:compiler_backend=disabled"
          && .\make install
      - name: Upload .NET bindings
        uses: actions/upload-artifact@v7
        with:
          name: frida-clr-windows-${{ matrix.arch }}
          path: ${{ env.FRIDA_PREFIX }}/bin/Frida.dll
      - name: Upload QML bindings
        if: matrix.arch == 'x86_64'
        uses: actions/upload-artifact@v7
        with:
          name: frida-qml-windows-${{ matrix.arch }}
          path: |
            ${{ env.FRIDA_PREFIX }}/lib/qml/
            !*.lib
            !*.pdb

