name: Patch and Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          repository: 'Ylarod/Florida'
          submodules: 'recursive'

      - name: Install Go toolchain
        uses: actions/setup-go@v5
        with:
          go-version-file: 'subprojects/frida-core/src/compiler/go.mod'
          cache-dependency-path: 'subprojects/frida-core/src/compiler/go.mod'

      - name: Set up NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b
          add-to-path: false

      - name: Add ANDROID_NDK_ROOT to environment
        run: echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - name: Configure
        run: |
          ./configure \
            --prefix=/build \
            --host=android-arm64 \
            --enable-portal \
            -- \
            -Dfrida-gum:devkits=gum,gumjs \
            -Dfrida-core:compiler_backend=enabled \
            -Dfrida-core:devkits=core

      - name: Compile
        run: make

      - name: Install
        run: make install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frida-patched-build-android-arm64
          path: /build
